Function
cmpsc-481-s22-m1/CASTanet pull request #17
Opened 2022-01-31 15:45 UTC by BaileyMatrascia

# Merge function counter

## pull request to merge function count function and function test into main

### Type of Change

- [X] Feature
- [ ] Bug fix
- [X] Documentation

## Contributors

- @BaileyMatrascia 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

2022-02-01 04:51 UTC, antlet requested changes
The new function looks good, though since it is a smaller version of `match_funcdefs` I would suggest looking into/discussing with the group ideas for a better function name. This might mean renaming just the function itself or changing the naming conventions for the whole file.

The test case also looks good, but the name should also be changed when the function's name is. 

The big change that is lacking is the implementation of the feature into the CLI. A new command needs to be created that calls your function. 

One more potential change regards the user story for this task. The customer specifies wanting to "know how many functions are in a Python module or package.". This implies that either the module/package needs to be specified when finding the function count or the function needs to output the function counts for all modules/packages separately. You should ask the customer to specify about what they expect from this user story.

2022-02-01 14:48 UTC, MaddyKapfhammer commented on castanet/counter.py
> +    """ function to for counting the number of functions in a Python program"""
Docstring should not have a space between the quotations and the first letter. First letter should be capitalized and the doscstring should end with a period.

2022-02-01 14:49 UTC, MaddyKapfhammer commented on tests/test_counter.py
> +    """Check that match_function identifies all of the comments in a directory."""
I believe this docstring should be rewritten.

2022-02-03 15:02 UTC, MaddyKapfhammer approved these changes

2022-02-03 15:04 UTC, antlet submitted a review, later dismissed
Looks great!

2022-02-03 15:05 UTC, MaddyKapfhammer approved these changes

2022-02-03 15:08 UTC, antlet approved these changes
Looks good

2022-02-03 15:08 UTC, merged